# Generated by Django 2.0.7 on 2018-07-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('FilePath', models.CharField(default=None, max_length=300)),
                ('Website', models.CharField(default=None, max_length=300)),
                ('City', models.CharField(default=None, max_length=300)),
                ('URL', models.CharField(default=None, max_length=300)),
                ('Category', models.CharField(default=None, max_length=300)),
                ('Percentage_Off', models.CharField(default=None, max_length=300)),
                ('Sales_Type', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
