# Generated by Django 2.0.7 on 2018-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
